# Generated by Django 5.0.4 on 2024-04-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_codebase_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebase',
            name='owner',
            field=models.TextField(),
        ),
    ]
